/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_orc_util_NativeMurmur3 */

#ifndef _Included_org_apache_orc_util_NativeMurmur3
#define _Included_org_apache_orc_util_NativeMurmur3
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     org_apache_orc_util_NativeMurmur3
 * Method:    hash32
 * Signature: ([BII)I
 */
JNIEXPORT jint JNICALL Java_org_apache_orc_util_NativeMurmur3_hash32
  (JNIEnv *, jclass, jbyteArray, jint, jint);

/*
 * Class:     org_apache_orc_util_NativeMurmur3
 * Method:    hash64
 * Signature: ([BIII)J
 */
JNIEXPORT jlong JNICALL Java_org_apache_orc_util_NativeMurmur3_hash64
  (JNIEnv *, jclass, jbyteArray, jint, jint, jint);

/*
 * Class:     org_apache_orc_util_NativeMurmur3
 * Method:    hash128
 * Signature: ([BIII)[J
 */
JNIEXPORT jlongArray JNICALL Java_org_apache_orc_util_NativeMurmur3_hash128
  (JNIEnv *, jclass, jbyteArray, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
