/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_orc_impl_NativeTreeReader */

#ifndef _Included_org_apache_orc_impl_NativeTreeReader
#define _Included_org_apache_orc_impl_NativeTreeReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_orc_impl_NativeTreeReader
 * Method:    nextVector
 * Signature: (Lorg/apache/hadoop/hive/ql/exec/vector/ColumnVector;[ZILorg/apache/orc/impl/BitFieldReader;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_apache_orc_impl_NativeTreeReader_nextVector
  (JNIEnv *, jclass, jobject, jbooleanArray, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
