/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_orc_impl_NativeTreeReader */

#ifndef _Included_org_apache_orc_impl_NativeTreeReader
#define _Included_org_apache_orc_impl_NativeTreeReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_orc_impl_NativeTreeReader
 * Method:    nextVector
 * Signature: ([Z[Z[BIZZ)I
 */
JNIEXPORT jint JNICALL Java_org_apache_orc_impl_NativeTreeReader_nextVector
  (JNIEnv *, jclass, jbooleanArray, jbooleanArray, jobject, jint, jboolean, jboolean);

#ifdef __cplusplus
}
#endif
#endif
